name: Codeberg Sync

on:
  push:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  mirror:
    uses: arcuru/actions/.github/workflows/codeberg-mirror.yml@31c804a9c15602300e5e292e80cac1ad5512a21a # v0.2.0
    with:
      destination: git@codeberg.org:arcuru/pokem.git
    secrets:
      ssh-private-key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
