name: "Deps: Hold Gate"

on:
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened, labeled, unlabeled]

permissions:
  contents: read
  pull-requests: read

jobs:
  hold:
    uses: arcuru/actions/.github/workflows/dependency-hold.yml@c8144123ad5a2c6316b7becab8233b68dfa637d9 # v0.2.1
