name: "Deps: Security Audit"

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  audit:
    uses: arcuru/actions/.github/workflows/security-audit.yml@c8144123ad5a2c6316b7becab8233b68dfa637d9 # v0.2.1
