name: "Deps: Hold Expiry"

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

permissions:
  pull-requests: write
  checks: write

jobs:
  update-hold:
    uses: arcuru/actions/.github/workflows/update-hold.yml@c8144123ad5a2c6316b7becab8233b68dfa637d9 # v0.2.1
