name: "Deps: Hold Expiry"

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update-hold:
    uses: arcuru/actions/.github/workflows/update-hold.yml@a7c938293186c1ba82fc32921d10c71734d1d21c # v0.1.0
